version: "3.8"

services:
  etcd:
    container_name: etcd
    image: quay.io/coreos/etcd:latest
    hostname: etcd
    restart: always
    tty: true
    command: etcd --name=etcd --advertise-client-urls=http://0.0.0.0:2379  --listen-client-urls=http://0.0.0.0:2379 --listen-peer-urls=http://0.0.0.0:238  --initial-advertise-peer-urls=http://0.0.0.0:2380
    environment:
      TZ: Asia/Shanghai
    ports:
      - "${ETCD_PORT_API:-2379}:2379"
      - "${ETCD_PORT_PEER:-2380}:2380"
    networks:
      - default

networks:
  default:
    name: bridge-default
    driver: bridge
    external: true