version: "3.8"

services:
  mongo:
    container_name: mongo
    image: mongo:latest
    hostname: mongo
    restart: always
    tty: true
    command: mongod --auth --bind_ip_all --port=27017 --dbpath=/data/db --logpath=/var/log/mongo.log --wiredTigerCacheSizeGB=8
    ports:
      - "${MONGO_PORT:-27017}:27017"
    environment:
      TZ: Asia/Shanghai
      MONGO_INITDB_DATABASE: admin
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
    volumes:
      - /opt/mongo/db:/data/db
      - /opt/mongo/log:/var/log
      - /opt/mongo/conf:/data/configdb
    networks:
      - default

networks:
  default:
    name: bridge-default
    driver: bridge
    external: true
