version: "3.8"

services:
  mysql:
    container_name: mysql
    image: mysql:latest
    hostname: mysql
    restart: always
    tty: true
    command: --default-authentication-plugin=mysql_native_password
    environment:
      TZ: Asia/Shanghai
#      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_ALLOW_EMPTY_PASSWORD: true
    ports:
      - "${MYSQL_PORT:-3306}:3306"
    volumes:
      - /opt/mysql/data:/var/lib/mysql
      - /opt/mysql/conf.d:/etc/mysql/conf.d
    networks:
      - default

networks:
  default:
    name: bridge-default
    driver: bridge
    external: true